// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class GetCoffeMakersListTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = Config.driverConfig();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void getCoffeMakersList() {
    // Test name: getCoffeMakersList
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://ulmarts.ru/");
    // 2 | click | xpath=//div[3]/div/div/a |  | 
    driver.findElement(By.xpath("//div[3]/div/div/a")).click();
    // 3 | click | xpath=//div[4]/ul/li[2]/a |  | 
    driver.findElement(By.xpath("//div[4]/ul/li[2]/a")).click();
    // 4 | runScript | window.scrollTo(0,540) |  | 
    js.executeScript("window.scrollTo(0,540)");
  }
}
