// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class GoToYandexMapsTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = Config.driverConfig();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void goToYandexMaps() {
        // Test name: goToYandexMaps
        // Step # | name | target | value | comment
        // 1 | open | / |  |
        driver.get("https://ulmarts.ru//");
        // 2 | click | xpath=//li/a |  |
        driver.findElement(By.xpath("//li/a")).click();
        // 3 | runScript | window.scrollTo(0,1570.6666259765625) |  |
        js.executeScript("window.scrollTo(0,1570.6666259765625)");
        // 4 | click | xpath=//ymaps[2]/ymaps/ymaps/ymaps/ymaps[2]/ymaps |  |
        vars.put("window_handles", driver.getWindowHandles());
        // 5 | selectWindow | handle=${win5663} |  |
        driver.findElement(By.xpath("//ymaps[2]/ymaps/ymaps/ymaps/ymaps[2]/ymaps")).click();
        vars.put("win5663", waitForWindow(2000));
        driver.switchTo().window(vars.get("win5663").toString());
    }
}
