// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WriteShopReviewTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = Config.driverConfig();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void writeShopReview() {
        // Test name: writeShopReview
        // Step # | name | target | value | comment
        // 1 | open | https://ulmarts.ru/goroda |  |
        driver.get("https://ulmarts.ru/goroda");
        // 2 | runScript | window.scrollTo(0,3330) |  |
        js.executeScript("window.scrollTo(0,3330)");
        // 3 | click | xpath=//div[17]/div/div/div/a |  |
        driver.findElement(By.xpath("//div[17]/div/div/div/a")).click();
        // 4 | runScript | window.scrollTo(0,3200) |  |
        js.executeScript("window.scrollTo(0,3200)");
        // 5 | runScript | window.scrollTo(0,4418.66650390625) |  |
        js.executeScript("window.scrollTo(0,4418.66650390625)");
        // 6 | click | xpath=//div[2]/input |  |
        driver.findElement(By.xpath("//div[2]/input")).click();
        // 7 | type | xpath=//div[2]/input | I |
        driver.findElement(By.xpath("//div[2]/input")).sendKeys("I");
        // 8 | click | xpath=//div[3]/input |  |
        driver.findElement(By.xpath("//div[3]/input")).click();
        // 9 | type | xpath=//div[3]/input | addr@example.com |
        driver.findElement(By.xpath("//div[3]/input")).sendKeys("addr@example.com");
        // 10 | click | xpath=//textarea |  |
        driver.findElement(By.xpath("//textarea")).click();
        // 11 | type | xpath=//textarea | some text |
        driver.findElement(By.xpath("//textarea")).sendKeys("some text");
        // 12 | click | xpath=//div[6]/input |  |
        driver.findElement(By.xpath("//div[6]/input")).click();
    }
}
